### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [nolit1/RLE#1]
1. Перенесите всю логику разбора аргументов в класс `Input`, а в `encode/decodeToFile` передавайте объект этого класса
2. Добавьте обработку аргумента с выходным файлом (см. задание)
3. Переименуйте поля `a` и `b` в классе `Input` во что-нибудь более осмысленное (хотя бы чтобы они соответствовали названиям аргументов)
4. (?) В методе `encode` вы используете цикл `for` и внутри этого цикла манипулируете счётчиком. Это немного путает читающего ваш код. Подумайте, может цикл `while` здесь подходит лучше?

**Comment by gagarski** [comment]
Сейчас ваш метод `Input.getOutputFileName()` не соответсвует заданию. Например, для файла `input.txt` следует формировать выходной файл `input.txt.rle` или `input.rle` (если, конечно, выходной файл не задан явно). 

В остальном, вроде, порядок.

**Comment by nolit1** [comment]
Понял, сейчас сделаю, спасибо

**Comment by nolit1** [comment]
То есть если задаётся имя конкретное, то мы RLE не прибавляем, если ничего не задано, то прибавляем?

**Comment by nolit1** [comment]
.rle

**Comment by gagarski** [comment]
@nolit1 

Если задано конкретное имя, то берём его, без `.rle`. Если не задоно, то имя входного файла с `.rle`.

**Comment by nolit1** [comment]
Сделал
